apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}
rules:
- apiGroups: ["azuredevops.krateo.io"]
  resources: ["connectorconfigs", "gitrepositories", "pipelines", "teamprojects", "runs"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

- apiGroups: ["azuredevops.krateo.io"]
  resources: ["gitrepositories/status", "pipelines/status", "teamprojects/status", "runs/status"]
  verbs: ["get", "patch", "update"]

- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]

- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
